/**
 * Random placeholder examples for the search input
 * These examples help users understand the variety of queries they can make
 */

export interface PlaceholderExample {
  fr: string;
  en: string;
  ja: string;
  it: string;
  es: string;
  de: string;
}

export const PLACEHOLDER_EXAMPLES: PlaceholderExample[] = [
  {
    fr: 'Un film ou une série avec Jennifer Aniston comme actrice principale, fin des années 90, disponible sur Amazon Prime',
    en: 'A movie or TV show with Jennifer Aniston as the lead actress, late 90s, available on Amazon Prime',
    ja: 'ジェニファー・アニストンが主演の90年代後半の映画やテレビ番組、Amazon Primeで視聴可能',
    it: 'Un film o una serie TV con Jennifer Aniston come attrice principale, fine anni 90, disponibile su Amazon Prime',
    es: 'Una película o serie con Jennifer Aniston como protagonista, finales de los 90, disponible en Amazon Prime',
    de: 'Ein Film oder eine Serie mit Jennifer Aniston in der Hauptrolle, Ende der 90er, auf Amazon Prime verfügbar',
  },
  {
    fr: 'Un thriller psychologique coréen récent sur Netflix',
    en: 'A recent Korean psychological thriller on Netflix',
    ja: 'Netflixの最新韓国サイコロジカルスリラー',
    it: 'Un thriller psicologico coreano recente su Netflix',
    es: 'Un thriller psicológico coreano reciente en Netflix',
    de: 'Ein aktueller koreanischer Psychothriller auf Netflix',
  },
  {
    fr: "Des films d'animation Studio Ghibli pour une soirée nostalgique",
    en: 'Studio Ghibli animated films for a nostalgic evening',
    ja: '懐かしい夜のためのスタジオジブリアニメ映画',
    it: 'Film di animazione Studio Ghibli per una serata nostalgica',
    es: 'Películas de animación de Studio Ghibli para una noche nostálgica',
    de: 'Studio Ghibli Animationsfilme für einen nostalgischen Abend',
  },
  {
    fr: 'Une comédie romantique française des années 2000',
    en: 'A French romantic comedy from the 2000s',
    ja: '2000年代のフランスロマンティックコメディ',
    it: 'Una commedia romantica francese degli anni 2000',
    es: 'Una comedia romántica francesa de los años 2000',
    de: 'Eine französische romantische Komödie aus den 2000ern',
  },
  {
    fr: 'Série de science-fiction avec des voyages dans le temps',
    en: 'Sci-fi series with time travel',
    ja: 'タイムトラベルのあるSF シリーズ',
    it: 'Serie di fantascienza con viaggi nel tempo',
    es: 'Serie de ciencia ficción con viajes en el tiempo',
    de: 'Science-Fiction-Serie mit Zeitreisen',
  },
  {
    fr: "Films d'horreur japonais classiques des années 90",
    en: 'Classic Japanese horror films from the 90s',
    ja: '90年代の古典的な日本のホラー映画',
    it: 'Film horror giapponesi classici degli anni 90',
    es: 'Películas de terror japonés clásicas de los años 90',
    de: 'Klassische japanische Horrorfilme aus den 90ern',
  },
  {
    fr: 'Documentaires sur la nature disponibles sur Disney+',
    en: 'Nature documentaries available on Disney+',
    ja: 'Disney+で視聴可能な自然ドキュメンタリー',
    it: 'Documentari sulla natura disponibili su Disney+',
    es: 'Documentales de naturaleza disponibles en Disney+',
    de: 'Naturdokumentationen auf Disney+ verfügbar',
  },
  {
    fr: 'Action avec des voitures et des courses',
    en: 'Action movies with cars and racing',
    ja: '車とレースのアクション映画',
    it: "Film d'azione con auto e corse",
    es: 'Películas de acción con coches y carreras',
    de: 'Actionfilme mit Autos und Rennen',
  },
  {
    fr: 'Quelque chose de léger et drôle pour me détendre',
    en: 'Something light and funny to relax',
    ja: 'リラックスするための軽くて面白いもの',
    it: 'Qualcosa di leggero e divertente per rilassarmi',
    es: 'Algo ligero y divertido para relajarme',
    de: 'Etwas Leichtes und Lustiges zum Entspannen',
  },
  {
    fr: 'Série policière britannique avec de bons dialogues',
    en: 'British crime series with good dialogue',
    ja: '良い対話のあるイギリスの犯罪シリーズ',
    it: 'Serie poliziesca britannica con buoni dialoghi',
    es: 'Serie policiaca británica con buenos diálogos',
    de: 'Britische Krimiserie mit guten Dialogen',
  },
  {
    fr: 'Films de super-héros Marvel récents',
    en: 'Recent Marvel superhero movies',
    ja: '最新のマーベルスーパーヒーロー映画',
    it: 'Film di supereroi Marvel recenti',
    es: 'Películas recientes de superhéroes de Marvel',
    de: 'Aktuelle Marvel-Superheldenfilme',
  },
  {
    fr: 'Drame historique sur la Seconde Guerre mondiale',
    en: 'Historical drama about World War II',
    ja: '第二次世界大戦の歴史ドラマ',
    it: 'Dramma storico sulla Seconda Guerra Mondiale',
    es: 'Drama histórico sobre la Segunda Guerra Mundial',
    de: 'Historisches Drama über den Zweiten Weltkrieg',
  },
  {
    fr: 'Anime avec des robots géants et des combats épiques',
    en: 'Anime with giant robots and epic battles',
    ja: '巨大ロボットと壮大な戦いのあるアニメ',
    it: 'Anime con robot giganti e battaglie epiche',
    es: 'Anime con robots gigantes y batallas épicas',
    de: 'Anime mit Riesenrobotern und epischen Kämpfen',
  },
  {
    fr: 'Comédie américaine des années 80 avec Eddie Murphy',
    en: '80s American comedy with Eddie Murphy',
    ja: 'エディ・マーフィーの80年代アメリカンコメディ',
    it: 'Commedia americana degli anni 80 con Eddie Murphy',
    es: 'Comedia americana de los años 80 con Eddie Murphy',
    de: 'Amerikanische Komödie der 80er mit Eddie Murphy',
  },
  {
    fr: 'Thriller nordique sombre et atmosphérique',
    en: 'Dark and atmospheric Nordic thriller',
    ja: '暗くて雰囲気のある北欧スリラー',
    it: 'Thriller nordico scuro e atmosferico',
    es: 'Thriller nórdico oscuro y atmosférico',
    de: 'Dunkler und atmosphärischer nordischer Thriller',
  },
  {
    fr: 'Films avec Leonardo DiCaprio dans un rôle dramatique',
    en: 'Movies with Leonardo DiCaprio in a dramatic role',
    ja: 'レオナルド・ディカプリオのドラマティックな役の映画',
    it: 'Film con Leonardo DiCaprio in un ruolo drammatico',
    es: 'Películas con Leonardo DiCaprio en un papel dramático',
    de: 'Filme mit Leonardo DiCaprio in einer dramatischen Rolle',
  },
  {
    fr: 'Comédies musicales récentes sur Disney+',
    en: 'Recent musicals on Disney+',
    ja: 'Disney+の最新ミュージカル',
    it: 'Musical recenti su Disney+',
    es: 'Musicales recientes en Disney+',
    de: 'Aktuelle Musicals auf Disney+',
  },
  {
    fr: 'Westerns modernes avec Clint Eastwood',
    en: 'Modern westerns with Clint Eastwood',
    ja: 'クリント・イーストウッドの現代西部劇',
    it: 'Western moderni con Clint Eastwood',
    es: 'Westerns modernos con Clint Eastwood',
    de: 'Moderne Western mit Clint Eastwood',
  },
  {
    fr: 'Séries de fantasy épique comme Game of Thrones',
    en: 'Epic fantasy series like Game of Thrones',
    ja: 'ゲーム・オブ・スローンズのような壮大なファンタジーシリーズ',
    it: 'Serie fantasy epiche come Game of Thrones',
    es: 'Series de fantasía épica como Juego de Tronos',
    de: 'Epische Fantasy-Serien wie Game of Thrones',
  },
  {
    fr: "Films d'espionnage britanniques des années 60",
    en: 'British spy films from the 60s',
    ja: '60年代のイギリススパイ映画',
    it: 'Film di spionaggio britannici degli anni 60',
    es: 'Películas de espías británicas de los años 60',
    de: 'Britische Spionagefilme aus den 60ern',
  },
  {
    fr: 'Documentaires culinaires sur Netflix',
    en: 'Culinary documentaries on Netflix',
    ja: 'Netflixの料理ドキュメンタリー',
    it: 'Documentari culinari su Netflix',
    es: 'Documentales culinarios en Netflix',
    de: 'Kulinarische Dokumentationen auf Netflix',
  },
  {
    fr: 'Films de guerre du Vietnam avec des acteurs célèbres',
    en: 'Vietnam War movies with famous actors',
    ja: '有名俳優のベトナム戦争映画',
    it: 'Film di guerra del Vietnam con attori famosi',
    es: 'Películas de la Guerra de Vietnam con actores famosos',
    de: 'Vietnamkriegsfilme mit berühmten Schauspielern',
  },
  {
    fr: 'Comédies italiennes classiques des années 70',
    en: 'Classic Italian comedies from the 70s',
    ja: '70年代の古典的なイタリアンコメディ',
    it: 'Commedie italiane classiche degli anni 70',
    es: 'Comedias italianas clásicas de los años 70',
    de: 'Klassische italienische Komödien aus den 70ern',
  },
  {
    fr: 'Séries de zombies post-apocalyptiques',
    en: 'Post-apocalyptic zombie series',
    ja: 'ポストアポカリプスゾンビシリーズ',
    it: 'Serie di zombie post-apocalittiche',
    es: 'Series de zombis postapocalípticas',
    de: 'Postapokalyptische Zombie-Serien',
  },
  {
    fr: "Films d'arts martiaux avec Jackie Chan",
    en: 'Martial arts movies with Jackie Chan',
    ja: 'ジャッキー・チェンの武術映画',
    it: 'Film di arti marziali con Jackie Chan',
    es: 'Películas de artes marciales con Jackie Chan',
    de: 'Kampfkunstfilme mit Jackie Chan',
  },
  {
    fr: 'Drames familiaux touchants disponibles sur Amazon Prime',
    en: 'Touching family dramas available on Amazon Prime',
    ja: 'Amazon Primeで視聴可能な感動的な家族ドラマ',
    it: 'Drammi familiari toccanti disponibili su Amazon Prime',
    es: 'Dramas familiares conmovedores disponibles en Amazon Prime',
    de: 'Berührende Familiendramen auf Amazon Prime verfügbar',
  },
  {
    fr: 'Films de pirates avec Johnny Depp',
    en: 'Pirate movies with Johnny Depp',
    ja: 'ジョニー・デップの海賊映画',
    it: 'Film di pirati con Johnny Depp',
    es: 'Películas de piratas con Johnny Depp',
    de: 'Piratenfilme mit Johnny Depp',
  },
  {
    fr: 'Séries policières scandinaves sombres',
    en: 'Dark Scandinavian crime series',
    ja: '暗いスカンジナビアの犯罪シリーズ',
    it: 'Serie poliziesche scandinave oscure',
    es: 'Series policiacas escandinavas oscuras',
    de: 'Dunkle skandinavische Krimiserien',
  },
  {
    fr: 'Films de danse contemporaine avec de la musique pop',
    en: 'Contemporary dance movies with pop music',
    ja: 'ポップミュージックのコンテンポラリーダンス映画',
    it: 'Film di danza contemporanea con musica pop',
    es: 'Películas de danza contemporánea con música pop',
    de: 'Zeitgenössische Tanzfilme mit Popmusik',
  },
  {
    fr: 'Biopics de musiciens célèbres des années 2010',
    en: 'Biopics of famous musicians from the 2010s',
    ja: '2010年代の有名ミュージシャンの伝記映画',
    it: 'Biografie di musicisti famosi degli anni 2010',
    es: 'Biopics de músicos famosos de los años 2010',
    de: 'Biopics berühmter Musiker aus den 2010ern',
  },
  {
    fr: 'Films de catastrophe naturelle avec des effets spéciaux impressionnants',
    en: 'Natural disaster movies with impressive special effects',
    ja: '印象的な特殊効果の自然災害映画',
    it: 'Film di catastrofi naturali con effetti speciali impressionanti',
    es: 'Películas de desastres naturales con efectos especiales impresionantes',
    de: 'Naturkatastrophenfilme mit beeindruckenden Spezialeffekten',
  },
  {
    fr: 'Comédies romantiques avec Sandra Bullock',
    en: 'Romantic comedies with Sandra Bullock',
    ja: 'サンドラ・ブロックのロマンティックコメディ',
    it: 'Commedie romantiche con Sandra Bullock',
    es: 'Comedias románticas con Sandra Bullock',
    de: 'Romantische Komödien mit Sandra Bullock',
  },
  {
    fr: "Séries de médecins dramatiques comme Grey's Anatomy",
    en: "Medical drama series like Grey's Anatomy",
    ja: 'グレイズ・アナトミーのような医療ドラマシリーズ',
    it: "Serie medical drama come Grey's Anatomy",
    es: "Series de drama médico como Grey's Anatomy",
    de: "Arztserien wie Grey's Anatomy",
  },
  {
    fr: 'Films de course automobile avec des voitures de sport',
    en: 'Racing movies with sports cars',
    ja: 'スポーツカーのレーシング映画',
    it: 'Film di corse automobilistiche con auto sportive',
    es: 'Películas de carreras con coches deportivos',
    de: 'Rennfilme mit Sportwagen',
  },
  {
    fr: 'Thrillers psychologiques avec des retournements de situation',
    en: 'Psychological thrillers with plot twists',
    ja: 'どんでん返しのあるサイコロジカルスリラー',
    it: 'Thriller psicologici con colpi di scena',
    es: 'Thrillers psicológicos con giros argumentales',
    de: 'Psychothriller mit Wendungen',
  },
  {
    fr: 'Films espagnols de Pedro Almodóvar',
    en: 'Spanish films by Pedro Almodóvar',
    ja: 'ペドロ・アルモドバルのスペイン映画',
    it: 'Film spagnoli di Pedro Almodóvar',
    es: 'Películas de Pedro Almodóvar con Penélope Cruz',
    de: 'Spanische Filme von Pedro Almodóvar',
  },
  {
    fr: 'Séries espagnoles comme La Casa de Papel',
    en: 'Spanish series like Money Heist',
    ja: 'ペーパー・ハウスのようなスペインのシリーズ',
    it: 'Serie spagnole come La Casa di Carta',
    es: 'Series españolas como Élite o La Casa de Papel',
    de: 'Spanische Serien wie Haus des Geldes',
  },
  {
    fr: 'Comédies espagnoles récentes sur Netflix',
    en: 'Recent Spanish comedies on Netflix',
    ja: 'Netflixの最新スペインコメディ',
    it: 'Commedie spagnole recenti su Netflix',
    es: 'Comedias españolas con Santiago Segura',
    de: 'Aktuelle spanische Komödien auf Netflix',
  },
  {
    fr: 'Films allemands sur la Seconde Guerre mondiale',
    en: 'German films about World War II',
    ja: '第二次世界大戦のドイツ映画',
    it: 'Film tedeschi sulla Seconda Guerra Mondiale',
    es: 'Películas alemanas sobre la Segunda Guerra Mundial',
    de: 'Deutsche Filme über den Zweiten Weltkrieg wie Der Untergang',
  },
  {
    fr: 'Thrillers allemands sombres comme Dark',
    en: 'Dark German thrillers like Dark',
    ja: 'ダークのようなドイツのダークスリラー',
    it: 'Thriller tedeschi oscuri come Dark',
    es: 'Thrillers alemanes oscuros como Dark',
    de: 'Deutsche Thriller-Serien wie Dark oder Babylon Berlin',
  },
  {
    fr: 'Comédies allemandes avec Til Schweiger',
    en: 'German comedies with Til Schweiger',
    ja: 'ティル・シュヴァイガーのドイツコメディ',
    it: 'Commedie tedesche con Til Schweiger',
    es: 'Comedias alemanas con Til Schweiger',
    de: 'Deutsche Komödien mit Til Schweiger oder Matthias Schweighöfer',
  },
  {
    fr: 'Films mexicains récents primés',
    en: 'Recent award-winning Mexican films',
    ja: '受賞歴のある最新メキシコ映画',
    it: 'Film messicani recenti premiati',
    es: 'Películas mexicanas de Guillermo del Toro o Alfonso Cuarón',
    de: 'Preisgekrönte mexikanische Filme',
  },
  {
    fr: 'Séries policières allemandes comme Tatort',
    en: 'German crime series like Tatort',
    ja: 'タトルトのようなドイツの犯罪シリーズ',
    it: 'Serie poliziesche tedesche come Tatort',
    es: 'Series policiacas alemanas como Tatort',
    de: 'Deutsche Krimiserien wie Tatort oder Der Alte',
  },
  {
    fr: 'Films argentins dramatiques',
    en: 'Argentine dramatic films',
    ja: 'アルゼンチンのドラマ映画',
    it: 'Film drammatici argentini',
    es: 'Películas argentinas con Ricardo Darín',
    de: 'Argentinische Dramen',
  },
  {
    fr: 'Documentaires allemands sur Netflix',
    en: 'German documentaries on Netflix',
    ja: 'Netflixのドイツドキュメンタリー',
    it: 'Documentari tedeschi su Netflix',
    es: 'Documentales alemanes en Netflix',
    de: 'Deutsche Dokumentationen auf Netflix oder Amazon Prime',
  },
];

/**
 * Get a random placeholder example for the specified language
 * @param language - The language code (fr, en, ja, it, es, de)
 * @returns A random placeholder text in the specified language
 */
export function getRandomPlaceholder(
  language: 'fr' | 'en' | 'ja' | 'it' | 'es' | 'de'
): string {
  const randomIndex = Math.floor(Math.random() * PLACEHOLDER_EXAMPLES.length);
  return PLACEHOLDER_EXAMPLES[randomIndex][language];
}
